/**
 * Shopify Connection Guide
 * Helps merchants configure Shopify Custom App and Webhooks
 */

'use client';

import { useState } from 'react';
import { Copy, Check, ExternalLink, AlertCircle } from 'lucide-react';
import { Button } from '@/shared/components/ui/button';

interface ShopifyConnectionGuideProps {
  webhookUrl: string;
  storeId: string;
}

export function ShopifyConnectionGuide({ webhookUrl, storeId }: ShopifyConnectionGuideProps) {
  const [copied, setCopied] = useState('');

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(''), 2000);
  };

  const steps = [
    {
      title: '1. Create Custom App in Shopify',
      desc: 'Go to Shopify Admin > Settings > Apps and sales channels > Develop apps',
      items: [
        { label: 'App name', value: 'Glow Loyalty' },
        { label: 'Required permissions', value: 'read_customers, read_orders' },
      ],
    },
    {
      title: '2. Configure Webhook (The Loop)',
      desc: 'Go to Shopify Admin > Settings > Notifications > Webhooks',
      items: [
        { label: 'Event', value: 'Order payment' },
        { label: 'Format', value: 'JSON' },
        { label: 'URL', value: webhookUrl, isCopy: true },
      ],
    },
    {
      title: '3. Save Webhook Secret',
      desc: 'Copy the Webhook Secret from Shopify and paste it in the form below',
      items: [],
    },
  ];

  return (
    <div className="space-y-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-slate-800">
          Connect Shopify Loop
        </h2>
        <p className="mt-2 text-slate-600">
          Enable automatic redemption tracking to monitor your loyalty program ROI
        </p>
      </div>

      {/* Alert */}
      <div className="flex gap-3 rounded-lg bg-blue-50 p-4">
        <AlertCircle className="h-5 w-5 flex-shrink-0 text-blue-600" />
        <div className="text-sm text-blue-900">
          <p className="font-medium">Why do we need this?</p>
          <p className="mt-1 text-blue-700">
            When customers use discount codes in Shopify, we automatically track redemptions
            and show you real revenue generated by your loyalty program.
          </p>
        </div>
      </div>

      {/* Steps */}
      {steps.map((step, idx) => (
        <div
          key={idx}
          className="rounded-lg border border-slate-100 bg-slate-50 p-4"
        >
          <h3 className="mb-2 font-semibold text-slate-700">{step.title}</h3>
          <p className="mb-3 text-sm text-slate-600">{step.desc}</p>

          <div className="space-y-2">
            {step.items.map((item) => (
              <div
                key={item.label}
                className="flex items-center justify-between rounded border border-slate-200 bg-white p-3 text-sm"
              >
                <span className="text-slate-500">{item.label}</span>
                <div className="flex items-center gap-2">
                  <code className="max-w-md truncate font-mono text-xs text-blue-600">
                    {item.value}
                  </code>
                  {item.isCopy && (
                    <button
                      onClick={() => copyToClipboard(item.value, item.label)}
                      className="rounded p-1 hover:bg-slate-100"
                      title="Copy to clipboard"
                    >
                      {copied === item.label ? (
                        <Check size={14} className="text-green-500" />
                      ) : (
                        <Copy size={14} className="text-slate-400" />
                      )}
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}

      {/* Action Button */}
      <a
        href="https://admin.shopify.com"
        target="_blank"
        rel="noopener noreferrer"
        className="block"
      >
        <Button className="w-full" size="lg">
          Go to Shopify Admin
          <ExternalLink className="ml-2 h-4 w-4" />
        </Button>
      </a>

      {/* Help Text */}
      <p className="text-center text-xs text-slate-500">
        Need help? Check our{' '}
        <a href="/docs/shopify-setup" className="text-blue-600 hover:underline">
          step-by-step guide
        </a>
      </p>
    </div>
  );
}


